apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: demo
  name: demo
spec:
  ports:
  - name: "8004"
    port: 8004
    targetPort: 8080
  selector:
    io.kompose.service: demo
status:
  loadBalancer: {}
