apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: kubeconsumer
  name: kubeconsumer
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kubeconsumer
    spec:
      containers:
      - image: localhost:5000/kubernetes-consumer
        name: kubeconsumer
        ports:
        - containerPort: 8080
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
status: {}
