apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: modelmaintainer
  name: modelmaintainer
spec:
  ports:
  - name: "8003"
    port: 8003
    targetPort: 8080
  selector:
    io.kompose.service: modelmaintainer
status:
  loadBalancer: {}
