apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: zipkinconsumer
  name: zipkinconsumer
spec:
  ports:
  - name: "8005"
    port: 8005
    targetPort: 8080
  selector:
    io.kompose.service: zipkinconsumer
status:
  loadBalancer: {}
