version: "3"

# additional propery from https://docs.docker.com/docker-cloud/apps/stack-yaml-reference/

services:

  monitor: 
    image: localhost:5000/kubernetes-monitor
    ports: 
      - "8001:8080"
  
  model-generator:
    image: localhost:5000/model-generator
    ports: 
      - "8002:8080"
    deploy:
#      autoredeploy: true
#       target_num_containers: 3

  activemq:
    image: webcenter/activemq:latest
    ports:
      - "61616:61616"
