version: "3"

services:

  monitor: 
    image: kubernetes-monitor
    ports: 
      - "8001:8080"
  
  model-generator:
    image: model-generator
    ports: 
      - "8002:8080"
  
  activemq:
    image: webcenter/activemq:latest

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"
      - "6831:6831"

  demo:
    image: tracing-example
    ports:
      - "8003:8080"