version: "3"

# additional propery from https://docs.docker.com/docker-cloud/apps/stack-yaml-reference/

services:

  kubeconsumer:
    image: localhost:5000/kubernetes-consumer
    ports: 
      - "8001:8080"
      - "8002:8081"

  modelgenerator:
    image: localhost:5000/model-generator
    ports: 
      - "8003:8080"
    deploy:
#      autoredeploy: true
#       target_num_containers: 3

  activemq:
    image: webcenter/activemq:latest
    ports:
      - "61616:61616"

  zipkinconsumer:
    image: localhost:5000/zipkin-consumer
    ports:
      - "8005:8080"

  zipkin:
      image: openzipkin/zipkin
      # Environment settings are defined here https://github.com/openzipkin/zipkin/tree/1.19.0/zipkin-server#environment-variables
      environment:
        - STORAGE_TYPE=mem
      ports:
        # Port used for the Zipkin UI and HTTP Api
        - 9411:9411

  demo:
    image: localhost:5000/tracing-example
    ports:
      - "8004:8080"