apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.hub.yml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  ports:
  - name: "8888"
    port: 8888
    targetPort: 80
  selector:
    io.kompose.service: gateway
status:
  loadBalancer: {}
