apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.hub.yml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: kubeconsumer
  name: kubeconsumer
spec:
  ports:
  - name: "8001"
    port: 8001
    targetPort: 8080
  - name: "8002"
    port: 8002
    targetPort: 8081
  selector:
    io.kompose.service: kubeconsumer
status:
  loadBalancer: {}
